"""Export utilities for retro game development engines and homebrew formats."""

from typing import List, Tuple
import os
import json
import numpy as np
from PIL import Image

from .palettes import Palette, rgb_to_hex


def export_c_header(
    indices: np.ndarray,
    palette: Palette,
    name: str = "sprite",
    output_path: str = "sprite.h",
) -> None:
    """
    Export image indices and palette as a C/C++ header file.
    Compatible with GBDK, devkitARM (GBA), Arduino, and retro C game engines.
    """
    h, w = indices.shape
    c_name = "".join([c if c.isalnum() else "_" for c in name])

    lines = [
        f"// Auto-generated by ImageToPixelArt CLI",
        f"#ifndef {c_name.upper()}_H",
        f"#define {c_name.upper()}_H",
        "",
        "#include <stdint.h>",
        "",
        f"#define {c_name.upper()}_WIDTH  {w}",
        f"#define {c_name.upper()}_HEIGHT {h}",
        f"#define {c_name.upper()}_PALETTE_SIZE {len(palette)}",
        "",
        f"// Palette (RGB888): {len(palette)} colors",
        f"const uint8_t {c_name}_palette[{len(palette)}][3] = {{",
    ]

    for r, g, b in palette:
        lines.append(f"    {{ 0x{r:02X}, 0x{g:02X}, 0x{b:02X} }},")
    lines.append("};")
    lines.append("")

    lines.append(f"// Sprite pixel indices: {w}x{h} ({w * h} bytes)")
    lines.append(f"const uint8_t {c_name}_data[{w * h}] = {{")

    for y in range(h):
        row_bytes = [f"0x{indices[y, x]:02X}" for x in range(w)]
        lines.append("    " + ", ".join(row_bytes) + ",")
    lines.append("};")
    lines.append("")
    lines.append(f"#endif // {c_name.upper()}_H")
    lines.append("")

    with open(output_path, "w", encoding="utf-8") as f:
        f.write("\n".join(lines))


def export_pico8_spritesheet(
    indices: np.ndarray,
    output_path: str = "sprite_pico8.txt",
) -> None:
    """
    Export 4-bit index values formatted for PICO-8 cartridges (__gfx__ section).
    Each hex digit corresponds to color 0..15.
    """
    h, w = indices.shape
    lines = []
    # Clamp to 16 colors (0..F)
    clamped = np.clip(indices, 0, 15)
    for y in range(h):
        row_str = "".join([f"{clamped[y, x]:x}" for x in range(w)])
        lines.append(row_str)

    with open(output_path, "w", encoding="utf-8") as f:
        f.write("\n".join(lines) + "\n")


def export_palette_json(
    palette: Palette,
    output_path: str = "palette.json",
) -> None:
    """Export palette as a structured JSON list of hex and RGB colors."""
    data = [
        {"index": i, "hex": rgb_to_hex(rgb), "rgb": list(rgb)}
        for i, rgb in enumerate(palette)
    ]
    with open(output_path, "w", encoding="utf-8") as f:
        json.dump(data, f, indent=2)
